### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by njsmith** [python-trio/pytest-trio#14]
Since I just filed a bunch of nitpicky issues, I wanted to also stop and mention two things I really liked:

* The parallel initialization of fixtures in `_resolve_coroutine_fixtures_in` is awesome

* You fixed MultiError tracebacks! I know it's still not as pretty as the regular pytest tracebacks, but I have wasted so much time trying to guess the meaning of incomplete MultiError tracebacks from pytest, and I also spent like an hour once trying to figure out how to hook traceback printing and totally failed. So: thank you!

**Comment by touilleMan** [comment]
:+1: 

Since you are here, I want to really thank you for the amazing job you've done on trio (and of course your [article that all started](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/)).
I've been fighting a lot with asyncio which really made me fell like it's not a pythonic library, trio on the other hand achieved of bringing simplicity to complex things which is what Python should all be about.

“Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.”  − Antoine de Saint-Exupéry

**Comment by njsmith** [comment]
> bringing simplicity to complex things which is what Python should all be about.

Aww :blush:. Thank you! That is exactly what I'm trying to do, so it's really great to hear that it's coming through.

**Comment by njsmith** [comment]
Whoops, mouse slipped and accidentally re-opened. Closing again...
